#!/bin/bash
CONFIG_FILE="$HOME/.config/ffr"

if [ $# -eq 0 ]; then
    sed '/^#>/Q' "$CONFIG_FILE"
else
    section="$1"
    awk -v section="$section" '
		/^#>/ &&
		section_notes { section_notes = 0 } /^#>/ &&
		(" " $0 " " ~ " #>" section " ") { section_notes = 1; next } 
		section_notes { print }
	' "$CONFIG_FILE"
fi

# example below of an ~/.config/ffr file, pound signs followed by a space need to be removed

# tar -czvf archive.tar.gz thing/ file
#   :  this command will print out when 'ffr' is ran without arguments
# #>ffmpeg #>ffm #>peg
# this line is printed when 'ffr ffmpeg', 'ffr ffm', or 'ffr peg' is ran
#   :  additional notes
