#!/bin/bash

NOTES_FILE="$HOME/.config/ffr"

if [ -z $1 ]; then
	awk '
		/^\#/ {exit} {print}
	' "$NOTES_FILE"
else
	awk -v topic="$1" '
		/^#\[/{in_block=index(tolower($0), tolower(topic))} in_block &&
		!/^#/{print $0}
	' "$NOTES_FILE"
fi

# example below of an ~/.config/ffr file, pound signs followed by a space need to be removed

# tar -czvf archive.tar.gz thing/ file
#   :  this command will print out when 'ffr' is ran without arguments
# #[ffmpeg][ffm][peg]#
# ffmpeg -i input.webm -vn -q:a 0 -f mp3 output.mp3
#   :  this command is printed when 'ffr ffmpeg', 'ffr ffm', or 'ffr peg' is ran
