#!/bin/sh
# This is a modified version of swindlesmccoop's note program

NOTES_FILE=$HOME/misc/notes

if [ "$1" = "-p" ]; then
  cat "$NOTES_FILE"
  exit 0
fi

nvim /tmp/note_temp
echo "[$(date)]" >> "$NOTES_FILE"
cat /tmp/note_temp >> "$NOTES_FILE"
echo "" >> "$NOTES_FILE"
rm /tmp/note_temp
