#!/bin/sh
# This is a modified version of swindlesmccoop's note program

NOTES_FILE=$HOME/misc/notes

# print option
if [ "$1" = "-p" ]; then
	cat "$NOTES_FILE"
	exit 0
fi

# enter note without editor
if [ "$#" -ge 1 ]; then
	echo "[$(date)]" >> "$NOTES_FILE"
	echo "$@" >> "$NOTES_FILE"
	echo "" >> "$NOTES_FILE"
	exit 0
fi

nvim +startinsert /tmp/note_temp

if [ -s /tmp/note_temp ]; then
	echo "[$(date)]" >> "$NOTES_FILE"
	cat /tmp/note_temp >> "$NOTES_FILE"
	echo "" >> "$NOTES_FILE"
	rm /tmp/note_temp
fi
