#!/bin/bash
# put the directory afterwards, if none, current is used
# renames all the files randomly to something
# P.S. doesn't check if there's another file with the same name

directory="${1:-.}"

if [ ! -d "$directory" ]; then
	echo "Error: $directory is not a valid directory."
	exit 1
fi

for file in "$directory"/*; do
	if [ -f "$file" ]; then
		base_name="${file##*}"
		extension="${base_name##*.}"
		if [ "$extension" != "$base_name" ]; then
			mv "$file" "$(mktemp --dry-run "$directory/XXXXXXXXXXXX").$extension"
			echo "Renamed '$file' to '$(mktemp --dry-run XXXXXXXXXXXX).$extension'"
		else
			mv "$file" "$(mktemp --dry-run "$directory/XXXXXXXXXXXX")"
			echo "Renamed '$file' to '$(mktemp --dry-run XXXXXXXXXXXX)'"
		fi
	fi
done
